#!/bin/bash
#manage my processes
while true; do
    read -p "Enter command: " cmd

    case $cmd in
        start)
            ./manage_my_process start
            ;;
        stop)
            ./manage_my_process stop
            ;;
        restart)
            ./manage_my_process restart
            ;;
        *)
            echo "Invalid command"
            ;;
    esac
done
