#!/bin/bash
#manage my processes
function manage_my_process() {
    while true; do
        echo "I am alive!" >> /tmp/my_process
        sleep 2
    done
}

if [[ $1 == "start" ]]; then
    manage_my_process &
    echo "manage_my_process started"
    echo $! > /var/run/my_process.pid
elif [[ $1 == "stop" ]]; then
    kill $(cat /var/run/my_process.pid)
    rm -f /var/run/my_process.pid
    echo "manage_my_process stopped"
elif [[ $1 == "restart" ]]; then
    kill $(cat /var/run/my_process.pid)
    rm -f /var/run/my_process.pid
    manage_my_process &
    echo "manage_my_process restarted"
else
    echo "Usage: manage_my_process {start|stop|restart}"
fi
